# Core Global Configuration
global:
  random_seed: 42
  max_workers: 8
  result_dir: "./results"
  is_ppl_filter: true

# Runtime Parameters
run_params:
  samples: 100
  dataset: "./data/bigvul_polars.parquet"
  iterations: 25
  algorithm: "beam"
  run_mode: "attack"
  label_map: "./models/finetuned_model_codebert_1/label_map.json"
  use_majority_voting: false

beam_params:
  beam_size: 3
  cand_chunk_size: 10
  early_stop_delta: 0.3
  beam_early_stop_strategy: patience
  beam_early_stop_patience: 2
  beam_early_stop_min_valid_vars: 3
  beam_enable_ast_check: true

# Target Models
model_zoo:
  CodeBERT: "./models/binary_diversevul_codebert_pure_dataset"
#  GraphCodeBERT: "./models/binary_diversevul_graphcodebert"
#  UniXCoder: "./models/binary_diversevul_unixcoder"

llm_generator_name: "models/qwen2.5-1.5b-code"

# Candidate Generation Configurations
lightweight_candidate:
  top_m: 15
  fasttext_model_path: "./models/pretrained/fasttext_cpp.bin"
  faiss_index_path: "./models/pretrained/faiss_cpp.index"
  faiss_vocab_path: "./models/pretarined/vocab_cpp.json"

heavyweight_candidate:
  top_k_mlm: 60
  top_n_keep: 50
  semantic_threshold: 0.87
  structural_semantic_threshold: 0.5
  minilm_model_path: "models/binary_diversevul_codebert_pure_dataset"
  context_ratio: 0.1
  preserve_style: true

# Attacker and Optimizer Configurations
irtg_attacker:
  top_k: 5
  rerank_after_llm_enrich: false
  llm_probe_quota: 2
  max_llm_enrich_attempts: 1

genetic_algorithm:
  pop_size: 40
  stagnation_threshold: 5
  mutation_rate_min: 0.1
  mutation_rate_max: 0.5
  elite_ratio: 0.25

# Other System Components
analyzer:
  lang: "cpp"
mlm_engine:
  model_name: "microsoft/codebert-base-mlm"
smoother:
  num_samples: 10
  variance_threshold: 0.05
  replace_prob: 0.5
  batch_size: 32